abbr g 'git'
abbr ga 'git add'
abbr gc 'git commit -v'
abbr gc! 'git commit --amend'
abbr gcb 'git checkout -b'
abbr gcl 'git clone --recursive'
abbr gclean 'git clean -fd'
abbr gco 'git checkout'
abbr gd 'git diff'
abbr gf 'git fetch'
abbr gl 'git pull'
abbr glo 'git log --oneline --decorate'
abbr gp 'git push'
abbr grh 'git reset HEAD'
abbr gss 'git status -sb'
abbr gst 'git status'
abbr gsu 'git submodule update'
abbr la 'ls -A'
abbr ll 'ls -alF'

