- name: Perform dist-upgrade
  apt:
    update-cache: yes
    upgrade: dist
  become: true

- name: Install additional packages through apt
  apt:
    name: ['git', 'vim', 'exuberant-ctags', 'curl', 'wget', 'shellcheck', 'tmux', 'golang', 'python3-pip', 'zsh']
    state: present
  become: true

- name: Install ripgrep
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
  become: true

- name: Update dot-files repository (including submodules)
  git:
    repo: 'https://github.com/folixg/dot-files.git'
    dest: ~/dot-files
    update: yes
    recursive: yes

- name: create ~/bin
  file:
    path: ~/bin
    state: directory

- name: Link config files
  file:
    src: ~/dot-files/{{ item }}
    dest: ~/.{{ item }}
    state: link
    force: yes
  with_items:
    - bash_aliases
    - bashrc
    - profile
    - zshrc
    - zshenv
    - gitignore
    - gitconfig
    - vimrc
    - vim
    - ctags
    - tmux.conf

- name: Clone fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: ~/.fzf
    depth: 1

- name: Setup fzf
  shell: ~/.fzf/install --no-fish --all

