- name: Perform dist-upgrade
  apt:
    update-cache: yes
    upgrade: dist
  become: true

- name: Install additional packages through apt
  apt:
    name: ['vim', 'exuberant-ctags', 'curl', 'wget', 'shellcheck', 'tmux']
    state: present
  become: true

- name: Install ripgrep
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
  become: true

- name: Update dot-files repository (including submodules)
  git:
    repo: 'https://github.com/folixg/dot-files.git'
    dest: ~/dot-files
    update: yes
    recursive: yes

- name: create ~/bin
  file:
    path: ~/bin
    state: directory

- name: Link config files
  file:
    src: ~/dot-files/{{ item }}
    dest: ~/.{{ item }}
    state: link
    force: yes
  with_items:
    - vim
    - vimrc
    - bashrc
    - bash_aliases
    - profile
    - gitignore
    - tmux.conf
    - ctags

