- name: Install additional packages through apt
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - i3
    - dunst
    - feh
    - xautolock
    - scrot

- name: Link i3 config
  file:
    src: ~/dot-files/i3
    dest: ~/.i3
    state: link
    force: yes
