- name: Link Xresources
  file:
    src: ~/dot-files/Xresources
    dest: ~/.Xresources
    state: link
    force: yes

- name: Create user fonts dir
  file:
    path: ~/.local/share/fonts
    state: directory
    mode: 0755

- name: Install Source Code Pro
  unarchive:
    src: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
    dest: ~/.local/share/fonts
    remote_src: True

- name: Install Font Awesome
  git: 
    repo: https://github.com/FortAwesome/Font-Awesome.git
    dest: ~/.local/share/fonts/fa

- name: Update font cache
  shell: fc-cache -f ~/.local/share/fonts

- name: Install Zathura
  apt:
    name: zathura
    state: present
  become: true

- name: Create Zathura config dir
  file:
    path: ~/.config/zathura
    state: directory
    mode: 0755

- name: Link Zathura config
  file:
    src: ~/dot-files/zathurarc
    dest: ~/.config/zathura/zathurarc
    state: link
    force: yes
