- name: Fetch gimme
  get_url:
    url: https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
    dest: ~/bin/gimme
    mode: 0755

- name: Install go using gimme
  shell: GIMME_GO_VERSION=1.8.1 ~/bin/gimme

