- name: Install zsh
  apt:
    name: zsh
    state: present
  become: true

- name: Link ~/.zshrc
  file:
    src: ~/dot-files/zshrc
    dest: ~/.zshrc
    state: link
    force: yes

- name: Link ~/.zshenv
  file:
    src: ~/dot-files/zshenv
    dest: ~/.zshenv
    state: link
    force: yes

- name: Clone fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: ~/.fzf
    depth: 1

- name: Setup fzf
  shell: ~/.fzf/install --no-fish --all
