- name: Create and set permissions for ~/.gnupg
  file:
    path: ~/.gnupg
    state: directory
    mode: 0700

- name: Set permissions for gpg config files
  file:
    path: ~/dot-files/gnupg/{{ item }}
    mode: 0600
  with_items:
    - dirmngr.conf
    - gpg.conf
    - gpg-agent.conf
    - sshcontrol  

- name: Link gpg config files
  file:
    src: ~/dot-files/gnupg/{{ item }}
    dest: ~/.gnupg/{{ item }}
    state: link
    force: yes
  with_items:
    - dirmngr.conf
    - gpg.conf
    - gpg-agent.conf
    - sshcontrol

- name: Create ~/.ssh
  file:
    path: ~/.ssh
    state: directory

- name: Link ~/.ssh/config
  file:
    src: ~/dot-files/ssh/config
    dest: ~/.ssh/config
    state: link
    force: yes
