#!/usr/bin/env zsh
# View markdown and rst in browser
view-html () {
  basename="${1%.*}"
  ext="${1#*.}"
  case "$ext" in
    "md"|"MD")
      format="markdown_github"
      ;;
    "rst"|"RST")
      format="rst"
      ;;
    *)
      echo "Unsupported filetype."
      return 1
      ;;
  esac
  pandoc -f "$format" -t html -o /var/run/user/$UID/"$ext"-preview.html "$basename"."$ext"
  firefox /var/run/user/$UID/"$ext"-preview.html
  return 0
}
