#!/usr/bin/env zsh
# View markdown and rst in browser
view-html () {
  # determine filetype by extension
  basename="${1%.*}"
  ext="${1#*.}"
  case "$ext" in
    "md"|"MD")
      format="markdown_github"
      ;;
    "rst"|"RST")
      format="rst"
      ;;
    *)
      echo "Unsupported filetype."
      return 1
      ;;
  esac
  # create the preview file
  pandoc -f "$format" -t html -o "$PWD/$ext-preview.html" "$basename.$ext"
  # check for xdotool
  if [ ! "$(which xdotool)" ]; then
    # simply open with firefox
    firefox "$PWD/$ext-preview.html"
    return 0
  else
    # check for existing preview window
    ffid=$(xdotool search --name "$PWD/$ext-preview.html - Mozilla Firefox")
    if [ ! "$ffid" ]; then
      firefox "$PWD/$ext-preview.html"
    else
      curid="$(xdotool getwindowfocus)"
      xdotool windowactivate "$ffid"
      xdotool key "ctrl+r"
      xdotool windowactivate "$curid"
    fi
  fi
  return 0
}

view-html $1
