- name: Install gnupg2
  apt:
    name: gnupg2
    state: present

- name: Create and set permissions for ~/.gnupg
  file:
    path: ~/.gnupg
    state: directory
    mode: 0700

- name: Set permissions for gpg config files
  file:
    path: ~/dot-files/gpg/{{ item }}
    mode: 0600
  with_items:
    - dirmngr.conf
    - gpg.conf
    - gpg-agent.conf

- name: Link gpg config files
  file:
    src: ~/dot-files/gpg/{{ item }}
    dest: ~/.gnupg/{{ item }}
    state: link
    force: yes
  with_items:
    - dirmngr.conf
    - gpg.conf
    - gpg-agent.conf

- name: Fetch public gpg key
  command: gpg2 --recv-key 0x1782EA931CF39ED8

