# color grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ls aliases
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# use GPG2 by default
alias gpg=gpg2

# alias for ubuntu docker
alias ubuntu='docker run --rm -it -v `pwd`:/mnt folixg/ubuntu'

# alias for go (use manually installed version over apt version)
if [ -e /usr/local/go/bin/go ] ; then
  alias go='/usr/local/go/bin/go'
fi

