# color grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# use GPG2 by default
alias gpg=gpg2

# helpers for gpg
alias lock-gpg-key=$DOTFILES/gpg/lock-gpg-key.sh
alias unlock-gpg-key=$DOTFILES/gpg/unlock-gpg-key.sh
alias gpg-focus=$DOTFILES/gpg/gpg-focus.sh

# alias for ubuntu docker
alias ubuntu='docker run --rm -it -v `pwd`:/mnt folixg/ubuntu'

# load go stable gimme environment
alias load-go='eval "$(gimme stable)"'
