- name: Install pip3
  apt:
    name: python3-pip
    state: present
  become: true

- name: Update pip
  pip:
    name: pip
    executable: pip3
    state: latest
  become: true

- name: Install flake8
  pip:
    name: flake8
    executable: pip3
  become: true

- name: Install pytest
  pip:
    name: pytest
    executable: pip3
  become: true

- name: Install autopep8
  pip:
    name: autopep8
    executable: pip3
  become: true
